### PR TITLE
Updated react-komposer, dependencies

### PR DESCRIPTION
**Pull request by markshust**

### CODE REVIEW

**Comment by markshust** [comment]
@arunoda can we pull these in, the wrapper packages are using pretty dated versions

**Comment by cpunion** [comment]
Please upgrade to `react-komposer@2.x`, `react-komposer@1.x` depends `mobx@2.x`, and it conflits with other libraries that depend `mobx@3`. `react-komposer@2.x` removes dependency of `mobx`.

**Comment by ndelangen** [comment]
Can I help maintain this?

@arunoda @sungwoncho @tomitrescak

**Comment by markshust** [comment]
@ndelangen i think this is part architecture problem. the fact that there are umbrella packages within mantra is part of the issue with it. you'll always have outdated deps that need updating. it looks like a smell to me. i think it's better to write abstractions into your local codebase for needed methods instead of looking at the mantra package for the versions.

**Comment by danielduan** [comment]
I've published `@storybook/mantra-core` to alleviate our peer dependency warnings for React 16. It includes an upgrade to `@storybook/react-komposer@2.x`which we forked and published as well. I'll accept PRs to bug fixes and maintenance for the foreseeable future if anyone is interested in opening a pull request too.

@cpunion if you're interested, feel free to use `@storybook/mantra-core` for the time being.

@ndelangen I don't think we should be maintaining this ecosystem for the sake of Storybook. We should really just migrate off of it.

**Comment by ndelangen** [comment]
I agree @danielduan, we should move away from unmaintained packages, or somehow get them to be maintained again, maintain them ourselves or otherwise.

By forking and republishing you've essentially chosen to start maintaining without the 'burden' of current users. Forking should be the last resort.

Having said that; I support your choice 100%, it seems these packages have been abandoned, and now no-one is left to transfer ownership even.

---

Still open to help get this package updated a bit. Give me access to the repo and npm, and I'll do it.

**Comment by sungwoncho** [comment]
@ndelangen I do not have admin access to this repo. I think @arunoda never did a proper handover before leaving Meteor. Therefore all Mantra related projects are in a limbo. I tried to ping him many times but sadly never got a reply.

**Comment by ndelangen** [comment]
@sungwoncho thanks for trying anyway!

**Pull request closed without merging**
